apiVersion: v1
kind: Pod
spec:
  containers:
    - name: herramientas
      image: alpine:3.23
      command:
        - cat
      tty: true
    - name: node
      image: node:24
      command:
        - cat
      tty: true
    - name: kubectl
      image: alpine/k8s:1.34.1
      command:
        - cat
      tty: true